### ISSUE TITLE
App DIR and History file DIR according to the ENV vars

### ISSUE THREAD

**Issue by Rub21** [vgeorge/osm-for-cities#21]
Currently, I am relying on a EFS (Elastic File System) to store both the PBF history files and git repositories. However, when it comes to running different environments like production and development.  the repositories are storing in the same place,  and it overwrites the repositories production and development,  Can we create different directories according to the ENV vars? e.g 👇 

```js 
/**
 * ENV DIR
 */

const ENV_DIR = process.env.NODE_ENV ? `${process.env.NODE_ENV}` : "development";

/**
 * Path to the runner app
 */
export const CLI_APP_DIR = path.join(basePath, `${ENV_DIR}/cli`);

```
https://github.com/vgeorge/osm-for-cities/blob/develop/config/index.js#L10

I added those, but does not work , Looks like there is more complex directory organization behind. 

cc. @vgeorge

**Comment by vgeorge** [comment]
Fixed by #23.
