### ISSUE TITLE
Add command to reset a context

### ISSUE THREAD

**Issue by vgeorge** [vgeorge/osm-for-cities#7]
There are some situations when a context reset might be necessary like when the presets are changed. It would be nice to have a command like `yarn cli context cities-of-brazil reset` that clears the history from the remote repository and erases the local git files to avoid conflicts.

cc @Rub21

**Comment by Rub21** [comment]
@vgeorge  I think Junior can help on this task, he may have some time.

cc. @yunica

**Comment by vgeorge** [comment]
Fixed by #19.
